version: '2'
services:
  db:
    image: postgres:10.0-alpine
    ports:
    - "5431:5432"
    volumes:
    - ./.dbdata://var/lib/postgresql/data
    environment:
    - POSTGRES_DB=simple
    - POSTGRES_USER=simple
    - POSTGRES_PASSWORD=simple